### ISSUE TITLE
error MSB6006: "app-java-builder.exe" exited with code -1.

### ISSUE THREAD

**Issue by dutchman71** [webbju/android-plus-plus#8]
Hi,

I'm trying to compile the sample projects with Java files using Android++. I have tried to compile the 'native-audio' and 'hello-gdbserver' project and am getting the same error message.

Any help greatly appreciated! :)

1>------ Rebuild All started: Project: hello-gdbserver, Configuration: Debug Android++.arm64-v8a ------
1>  [NativeCompile] hello-gdbserver.c
1>  [NativeLink] hello-gdbserver.obj
1>  hello-gdbserver.vcxproj -> C:\build\bin\android\vs14.0\hello-gdbserver\debug\arm64-v8a\libhello-gdbserver.so
1>  hello-gdbserver.vcxproj -> C:\build\bin\android\vs14.0\hello-gdbserver\debug\arm64-v8a\libhello-gdbserver.debug
1>  [NativeStrip] libhello-gdbserver.so
1>  symbolic link created for C:\build\bin\android\vs14.0\hello-gdbserver\debug\arm64-v8a.build-id\2f\73b1ed29a39e71378aa7616575a52e14c52a5d.debug <<===>> C:\build\bin\android\vs14.0\hello-gdbserver\debug\arm64-v8a\libhello-gdbserver.debug
1>  [AndroidAapt] AndroidManifest.xml
1>  [JavaBuilder] R.java
1>  Stack trace:    at app_java_builder.Program.ValidateArguments()
1>     at app_java_builder.Program.Main(String[] args)
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application Type\Android++\ProjectTypes\DeployViaMsBuild\AndroidJava.targets(93,5): error MSB6006: "app-java-builder.exe" exited with code -1.

**Comment by webbju** [comment]
Hey,

This will occur for one of 4 reasons; 

1. app-java-builder can't find the JDK.
2. app-java-builder can't find `javac.exe` under `<JDK>/bin`.
3. app-java-builder can't find `jar.exe` under `<JDK>/bin`.
4. app-java-builder can't find a specified manifest (unlikely unless you've changed settings).

First guess is that this is happening because you've not set an `JAVA_HOME` environment variable to point to the root of a JDK distribution.  Have you read the 'getting started' guide? https://github.com/webbju/android-plus-plus/blob/master/docs/getting_started.txt
